### PR TITLE
Fixup recent UX changes

### PR DESCRIPTION
**Pull request by TaiWilkin**
## Overview

- Increases the font size of the OSHub id on the details page to 18px
- Makes the claim description full-width and moves it to the last spot
- Prevents reloading the facility search when navigating to details and back
- Restores location in list when returning to search from details
     - List location is reset to the top when a new search is completed
     - If the user refreshes the page while on the details page, the search will be rerun and the list location will be reset to the top
- Restores the map in mobile view on the homepage

Connects #2133, #2127

## Demo

Sep-14-2022 10-32-57

Screen Shot 2022-09-14 at 10 33 51 AM

## Notes

The scroll-to-location consistently returns the user to approximately the correct location, but sometimes is a little bit off. I've spent some time attempting to tweak it, but I think this is as accurate as we'll get without spending significantly more time on it. 

I based this on Jacob's PR to handle merge conflicts.

## Testing Instructions

* Run `./scripts/server
* View the map on the homepage on mobile
* Run a search
* Scroll the list
* Navigate to a facility, then back using the back button on screen
* Navigate to a facility, then back using the browser back button
* Navigate to a facility with a claim description

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Review by jwalgran — COMMENTED** [review]
When returning from the details page to the search results, the results lists is scrolled up to the top.

We are storing the scroll position in Redux (under `ui.scrollTop`) and this Codepen example linked to from https://github.com/seatgeek/react-infinite/issues/267#issuecomment-395940059 makes think that we could restore the scroll position.

https://codesandbox.io/s/v1vlz0j293?file=/src/index.js

**Review by jwalgran — COMMENTED** [review]
Actually, I missed that we already have this block

```
    const [hasScrolled, setHasScrolled] = useState(false);
    const scrollElements = Array.from(
        document.getElementsByClassName('infinite-scroll'),
    );
    if (!hasScrolled && scrollElements.length) {
        setHasScrolled(true);
        // The timeout allows persisted data to be restored before scroll is attemped
        setTimeout(() => {
            scrollElements.forEach(x => {
                x.scrollTo(0, scrollTop);
            });
        }, 100);
    }
````

I do now see it trying to set the scroll position, but it is not returning to the correct spot for me.

**Review by jwalgran — APPROVED** [review]
I confirmed all of the changes except for the scroll restoration. I don't think we should block merging the PR but we will need further work on the scroll restoration portion. I observed 2 issues:. 

- The further down the list I scrolled the less accurate the scroll restoration appeared to be.
- Repeated scroll-click-back sequences would sometimes result in the scroll restoration breaking. Returning to the details page would result in the list returning to the top.

**Comment by TaiWilkin** [comment]
I've created a follow-up issue for the scroll restoration: https://github.com/open-apparel-registry/open-apparel-registry/issues/2150

**Pull request merged**
