### PR TITLE
Correct Facility Parent Company link

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

There is no detail page for Facility Parent Company entities, as both Claim Contributors and Facility Parent Company links open the same page. In cases when the IDs of the two are not in sync, clicking the Facility Parent Company link would go to the wrong page.

By making the link always point to the Claim Contributor's id, we ensure that it is always correct.

Connects #729 

## Testing Instructions

* Follow the instructions in the issue to simulate a situation where the user id and parent company id are out of sync
* Submit a claim
* Login as `c1@example.com` and go to the dashboard to view its details
* Click the Claim Contributor link. Ensure it works.
* Click the Facility Parent Company link. Ensure it works.

## Checklist

- [x] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by kellyi** [comment]
Testing this out and I don't think it's doing the correct thing:

For this link, it should go to the contributor page for "Civil Society Organization G" but instead it is going to "Factory A":

Screen Shot 2019-09-09 at 1 34 49 PM

**Comment by kellyi** [comment]
Chatted about this and it seems like we need to update the serializer to return the correct id value. We'll also need to update https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/app/src/components/FacilityDetailSidebarClaimedInfo.jsx#L85 to match whatever changes we decide to make to the serializer and the dashboard claim details page.

**Comment by rajadain** [comment]
I reverted the original front-end implementation and took another look at the serializer. Turns out we were inconsistent about the parent company's `id`, so I standardized to using the company's admin's `id`. This fixes the link issue on the front-end as well. Ready for another look.

**Comment by kellyi** [comment]
Heads up that there's a merge conflict in the CHANGELOG file again.

**Comment by kellyi** [comment]
This has another merge conflict.

**Comment by rajadain** [comment]
That should fix it.

**Comment by rajadain** [comment]
Thanks for taking a look, and for talking me through this. Will merge when green.

**Pull request merged**
