### PR TITLE
Implement Source model - Step 3

### PR DESCRIPTION
**Pull request by jwalgran**
## Overview

The third step of a three step process to add a Source model between facility lists and list items, allowing for the submission of individual facilities.

Each step in the process is intended to be released separately and maintain backward compatibility.

This is a "cleanup" step that removes fields made redundant by the Source model.

Connects #817
Depends on #856
Depends on #857

## Notes

This is the third of three pull requests to be deployed separately.

This PR is targeted at `jcw/source-model-2` because it depends on it. 

NOTE that this includes destructive migration. Going back to another develop-based branch will require a `resetdb`.

## Testing Instructions

* Checkout `develop` and run `./scripts/resetdb` and `./scripts/manage liststosources`
* Checkout this branch. Run `./scripts/manage migrate`
* Exercise every list/item/facility related feature
  * Log in as `c2@example.com`
  * Search for `regina miracle intimate` and view the details of the matching facility. Verify that the "Other locations," "Also known as," "Other addresses," and "Contributors" sections are populated.
  * Click the "Claim this facility" link and verify that you can successfully submit the claim.
  * In a new private browser window
    * Log in as `c1@example.com`.
    * Browse http://localhost:6543/dashboard/claims/1 and approve the claim
  * Back in the original browser window, refresh the "Regina" facility details page and click "Update facility details"
    * Enter a few field values and save the form
  * Copy the OAR ID
  * Browse http://localhost:8081/api/docs/#!/facilities/facilities_get_facility_history and submit the OAR ID. Verify that the history contains `CREATE`, `ASSOCIATE`, `CLAIM`, and `CLAIM_UPDATE`	events.
  * Browse http://localhost:6543/contribute and upload [other-location-test.csv.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/3692205/other-location-test.csv.zip)
  * Fully process the list. Verify there are no processing errors.
    * `./scripts/manage batch_process --list-id 16 --action parse`
    * `./scripts/manage batch_process --list-id 16 --action geocode`
    * `./scripts/manage batch_process --list-id 16 --action match`
  * Browse http://localhost:6543/lists/16
    * Reject one of the pending matches, accept the other. Verify that the process completes without error.
  * Back in the private browser window (superuser account) browse http://localhost:8081/admin/reports/. 
    * Run all the reports and verify that they don't return errors. NOTE several of the reports will not contain any results when run against the development database.

## Checklist

- [x] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by rajadain** [comment]
This has merge conflicts preventing review. Will take another look once they've been resolved.

**Comment by jwalgran** [comment]
I rebased this on the latest `jcw/source-model-2`, which I rebased on the latest `develop`. Conflicts resolved.

**Comment by rajadain** [comment]
Everything looks good. The only clarifying question I have is that even though I marked rejected one of the matches and confirmed the other one, I don't see anything in the Rejected Matches report:

image

Is that expected?

**Comment by rajadain** [comment]
Oh wait I was testing on `jcw/source-model-2` not `3` 🤦‍♂ 

I'll take a look at `3` once the new merge conflicts have been addressed.

**Comment by jwalgran** [comment]
The reports are designed to only count full months, so actions taken in October will not appear.

**Comment by jwalgran** [comment]
I rebased and retargeted this at `develop`, which took care of the conflicts. Ready for review.

**Comment by rajadain** [comment]
Seeing this crash:

```
Environment:


Request Method: GET
Request URL: http://localhost:8081/admin/reports/facility-list-items-uploaded/

Django Version: 2.2.5
Python Version: 3.7.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.gis',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_gis',
 'rest_framework_swagger',
 'rest_auth',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_auth.registration',
 'watchman',
 'simple_history',
 'waffle',
 'api',
 'web',
 'ecsmanage']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'spa.middleware.SPAMiddleware',
 'rollbar.contrib.django.middleware.RollbarNotifierMiddlewareExcluding404',
 'simple_history.middleware.HistoryRequestMiddleware',
 'waffle.middleware.WaffleMiddleware',
 'api.middleware.RequestLogMiddleware']



Traceback:

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  82.                 return self.cursor.execute(sql)

The above exception (column i.facility_list_id does not exist
LINE 8:          JOIN api_facilitylist l on i.facility_list_id = l.i...
                                            ^
) was the direct cause of the following exception:

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/usr/local/src/api/admin.py" in report_view
  32.         context = run_report(name)

File "/usr/local/src/api/reports.py" in run_report
  35.             cursor.execute(report_sql)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  99.             return super().execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in execute
  67.         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute_with_wrappers
  76.         return executor(sql, params, many, context)

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  84.                 return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.7/site-packages/django/db/utils.py" in __exit__
  89.                 raise dj_exc_value.with_traceback(traceback) from exc_value

File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py" in _execute
  82.                 return self.cursor.execute(sql)

Exception Type: ProgrammingError at /admin/reports/facility-list-items-uploaded/
Exception Value: column i.facility_list_id does not exist
LINE 8:          JOIN api_facilitylist l on i.facility_list_id = l.i...
                                            ^

```

image

For this report: http://localhost:8081/admin/reports/facility-list-items-uploaded/ "Facility List Items Uploaded"

**Comment by jwalgran** [comment]
I fixed the facility list items updated report in e479785 and rebased. I ran the previous SQL statement and the revised SQL statement against production and verified that they have the same counts

```
openapparelregistry=> SELECT
openapparelregistry->   CAST (date_part('month', i.created_at) AS int) AS month,
openapparelregistry->   CASE WHEN u.email LIKE '%openapparel.org%' THEN 'y' ELSE 'n' END AS is_public_list,
openapparelregistry->   COUNT(*) AS item_count
openapparelregistry->   FROM api_facilitylistitem i
openapparelregistry->          JOIN api_source s on i.source_id = s.id
openapparelregistry->          JOIN api_contributor c ON s.contributor_id = c.id
openapparelregistry->          JOIN api_user u ON u.id = c.admin_id
openapparelregistry->  WHERE date_part('month', i.created_at) != date_part('month', now())
openapparelregistry->  GROUP BY date_part('month', i.created_at), is_public_list
openapparelregistry->  ORDER BY date_part('month', i.created_at), is_public_list;
 month | is_public_list | item_count
-------+----------------+------------
     3 | n              |       8429
     3 | y              |       2115
     4 | n              |       5362
     4 | y              |       1825
     5 | n              |       1611
     6 | n              |       8479
     6 | y              |       1679
     7 | n              |       1704
     8 | n              |       1996
     8 | y              |       1130
     9 | n              |       4305
     9 | y              |        717
(12 rows)

openapparelregistry=> SELECT
openapparelregistry->   CAST (date_part('month', i.created_at) AS int) AS month,
openapparelregistry->   CASE WHEN u.email LIKE '%openapparel.org%' THEN 'y' ELSE 'n' END AS is_public_list,
openapparelregistry->   COUNT(*) AS item_count
openapparelregistry->   FROM api_facilitylistitem i
openapparelregistry->          JOIN api_facilitylist l on i.facility_list_id = l.id
openapparelregistry->          JOIN api_contributor c ON l.contributor_id = c.id
openapparelregistry->          JOIN api_user u ON u.id = c.admin_id
openapparelregistry->  WHERE date_part('month', i.created_at) != date_part('month', now())
openapparelregistry->  GROUP BY date_part('month', i.created_at), is_public_list
openapparelregistry->  ORDER BY date_part('month', i.created_at), is_public_list;
 month | is_public_list | item_count
-------+----------------+------------
     3 | n              |       8429
     3 | y              |       2115
     4 | n              |       5362
     4 | y              |       1825
     5 | n              |       1611
     6 | n              |       8479
     6 | y              |       1679
     7 | n              |       1704
     8 | n              |       1996
     8 | y              |       1130
     9 | n              |       4305
     9 | y              |        717
(12 rows)
```

**Comment by jwalgran** [comment]
Thanks for the reviews.

**Pull request merged**
