### PR TITLE
Enable viewing and editing profiles

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR enables viewing and editing profile data.

For logged in users, their profiles are now editable as depicted below. Edits required a password for confirmation and are limited to the following fields:

- name
- description
- contributor type
- other contributor type
- website

... all of which live on the contributor model

Profiles for other users are view-only.

I also updated the Facility Details page to have links to the contributor profiles.

Connects #104

## Demo

view-edit-profile
facility-profile-link
edit-profile-errors

## Notes

0f6e4cd  is an unrelated commit to fix a map loading bug, but I have it here so I could test it out in the course of working on this.

## Testing

- get this branch, then resetdb and register for two accounts
- sign in to one of the accounts and visit your profile page, verifying that it shows up as editable
- search for some facilities and then visit a details page. verify that there is now a link from any contributors to their profile pages and that those are view-only
- edit your profile and attempt to save it. verify that
   - not including a required field leads to an error message
   - an incorrect password shows an error message
   - successfully saving shows the toast and updates your profile data and, if it's different, the name in the app header
- run `./scripts/test` and verify that they pass

### CODE REVIEW

**Comment by kellyi** [comment]
Rebased on develop.

**Comment by rajadain** [comment]
Can we hide the "Website (Optional)" field title in read-only mode if the website is not specified? It looks a little odd.

image

**Comment by kellyi** [comment]
> Can we hide the "Website (Optional)" field title in read-only mode if the website is not specified? It looks a little odd.

Sure!

**Comment by kellyi** [comment]
> Can we hide the "Website (Optional)" field title in read-only mode if the website is not specified? It looks a little odd.

Handled in 282112ba604ddd83e463415b8767f3bc5aec18d2

**Comment by kellyi** [comment]
2ce21d8352510244c6327f2465c0ec19bc6cb31a fixes a bug in which the facility details data was sending back the contributor IDs rather than the contributor user IDs, which meant that the profile links created from those IDs were incorrect.

**Pull request merged**
