### PR TITLE
Use HubSpot for mailing list

### PR DESCRIPTION
**Pull request by TaiWilkin**
## Overview

Replaces the existing Mailchimp integration with HubSpot.

Connects #1944 

## Demo

Dev account
Screen Shot 2022-09-26 at 9 23 35 AM

Real OSHub subscription
Screen Shot 2022-09-26 at 9 58 51 AM

## Notes

I added the HubSpot variables to terraform on AWS, but didn't remove Mailchimp. We'll need to remove the Mailchimp variables once this is successfully merged.

## Testing Instructions

* Run `./scripts/server`. Sign up for an account and check the mailing list checkbox. Since you have no `HUBSPOT_API_KEY` set up, you'll be registered but not added to a mailing list. There shouldn't be an error.
* I will send you the test account API key and subscription ID directly. (Note: This key is only valid for 90 days, and applies to a developer account I set up just for testing this.) Add them to your `.env` file:
```
HUBSPOT_API_KEY={key}
HUBSPOT_SUBSCRIPTION_ID={id}
```
* Sign up for an account and check the mailing list checkbox. 
* Using Postman or similar, send a GET request to `https://api.hubapi.com/communication-preferences/v3/status/email/{EMAIL}` with EMAIL being the email you used to sign up. For authentication, use the API_KEY as a Bearer token. You should receive an object with two subscriptions listed. The one for "Open Supply Hub News and Updates" should be SUBSCRIBED. 
* If desired, you can also attempt this with the real OSHub API key and subscription id (see the OSHub terraform variables), but you'll be signed up for the real email subscription with whichever email you use. 

## Checklist

- [x] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Review by jwalgran — APPROVED** [review]
Nice job. I confirmed that this was working by following the test instructions.

Screen Shot 2022-09-26 at 4 23 57 PM

@nanotubing NOTE that as you set up the production stack make sure the tfvars include the new `hubspot_api_key` and `hubspot_subscription_id` variables.

**Comment by nanotubing** [comment]
> @nanotubing NOTE that as you set up the production stack make sure the tfvars include the new `hubspot_api_key` and `hubspot_subscription_id` variables.

just to confirm, the mailchimp variables are not necessary for the OS Hub production stack?

**Comment by TaiWilkin** [comment]
@nanotubing Correct. We can remove them from OSHub staging as well once this is merged.

**Comment by TaiWilkin** [comment]
Thank you for reviewing!

**Pull request merged**
