### PR TITLE
mobile optimization for map ui

### PR DESCRIPTION
**Pull request by designmatty**
## Overview

I had to rework the navbar component quite a bit to make this work. There's also a known bug with the select language dropdown, where you can't scroll horizontally within the dropdown. This is an issue with the iframe, which I can't tap in to.

In general, this is focused on the map UI.

**Main view:**
image

**Facility view:**
image

**Mobile menu:**
image

## Testing Instructions

* Test small screens

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by jwalgran** [comment]
The CI build failed on several eslint errors

```
$ eslint src/ --ext .js --ext .jsx

/usr/local/src/src/components/Navbar.jsx
    1:15   error  A space is required after '{'                            object-curly-spacing
    1:32   error  A space is required before '}'                           object-curly-spacing
   51:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent
   91:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent
   92:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent
   98:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent
  103:31   error  Missing trailing comma                                   comma-dangle
  149:28   error  A space is required after '{'                            object-curly-spacing
  149:46   error  A space is required before '}'                           object-curly-spacing
  159:100  error  A space is required after '{'                            object-curly-spacing
  159:117  error  A space is required before '}'                           object-curly-spacing
  162:6    error  Missing semicolon                                        semi
  176:6    error  Missing semicolon                                        semi
  180:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent
  195:9    error  Expected indentation of 12 space characters but found 8  react/jsx-indent

/usr/local/src/src/components/NavbarLoginButtonGroup.jsx
  117:67  error  Unexpected usage of singlequote  jsx-quotes

/usr/local/src/src/components/ZoomToSearchControl.jsx
   5:8   error  'COLOURS' is defined but never used                                                                no-unused-vars
  19:50  error  Missing trailing comma                                                                             comma-dangle
  33:1   error  Expected indentation of 12 spaces but found 13                                                     indent
  33:14  error  Expected indentation of 12 space characters but found 13                                           react/jsx-indent
  34:17  error  Expected indentation of 17 space characters but found 16                                           react/jsx-indent-props
  35:17  error  Expected indentation of 17 space characters but found 16                                           react/jsx-indent-props
  36:13  error  The closing bracket must be aligned with the line containing the opening tag (expected column 14)  react/jsx-closing-bracket-location
  37:17  error  Expected indentation of 17 space characters but found 16                                           react/jsx-indent
  45:13  error  Expected closing tag to match indentation of opening                                               react/jsx-closing-tag-location
  45:13  error  Expected indentation of 13 space characters but found 12                                           react/jsx-indent

✖ 26 problems (26 errors, 0 warnings)
  25 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by jwalgran** [comment]
@designmatty We talked with Natalie and Katie today and they said it was ok to hide the footer on mobile.

**Comment by designmatty** [comment]
This doesn't seem to be an issue related to any of the changes I made. I tried pulling up production on the same device configuration and got the same error. I'm happy to look into it though.

**Comment by designmatty** [comment]
@jwalgran I removed the footer and made a few minor tweaks for better performance and more consistency across all pages. 

I also had no luck determining the issue on ios 9. I did discover it persist in both chrome and safari on ios9.

**Comment by designmatty** [comment]
I just did a little bit more digging on the rendering issue. This is a known Turf issue. https://github.com/Turfjs/turf/issues/1243

**Comment by designmatty** [comment]
Good catch @jwalgran. Quick fix for that.

**Pull request merged**
