### PR TITLE
Text Fixes

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Wraps long filenames, swaps copy between My Lists and Individual List views.

Connects #1750 
Connects #1753 

## Demo

image

image

## Testing Instructions

* Upload a list with a really long name, like [OAR_Contributor_Template_CSV_with_a_ridiculously_long_name_that_will_break_all_column_widths_no_matter_how_big_your_screen_is_really_i_mean_really.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8316136/OAR_Contributor_Template_CSV_with_a_ridiculously_long_name_that_will_break_all_column_widths_no_matter_how_big_your_screen_is_really_i_mean_really.csv)
  - [ ] Ensure it wraps correctly
* Go to the My Lists and Individual List Views
  - [ ] Ensure they reflect correct copy

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by rajadain** [comment]
Good catch! Fixed in [da8bf42](https://github.com/open-apparel-registry/open-apparel-registry/pull/1756/commits/da8bf427cdc870ad0711126ca319eaa946b297ba)

**Comment by rajadain** [comment]
As of [aeac079](https://github.com/open-apparel-registry/open-apparel-registry/pull/1756/commits/aeac07909bfec6f6105d111497798f9bca57819f):

image

image

image

**Comment by TaiWilkin** [comment]
Taking a look

**Review by TaiWilkin — APPROVED** [review]
Working well, thanks for getting this together so quickly!

**Pull request merged**
