### PR TITLE
Add reports to count API requests and API token creation

### PR DESCRIPTION
**Pull request by jwalgran**
## Overview

Add reports to count API requests and API token creation for quarterly metrics reporting.

Connects  #832

## Testing Instructions

These instructions assume that you have run `./scripts/resetdb`

* Log in as c2@example.com
* Browse http://localhost:6543/profile/2 and create an API token. Copy and save it for later.
* Run `./scripts/manage dbshell` and execute the following query to "backdate" the token
```sql
UPDATE authtoken_token SET created = created - interval '2 months';
```
* Browse http://localhost:8081/admin/reports/api-tokens/ and verify that a token count of `1` appears
* Make an API request
```
curl -H 'Authorization: Token YOUR_TOKEN_HERE' "http://localhost:8081//api/facilities/?pageSize=1
```
* Run `./scripts/manage dbshell` and execute the following query to "backdate" the request
```sql
UPDATE api_requestlog SET created_at = created_at - interval '2 months';
```
* Browse http://localhost:8081/admin/reports/api-requests/ and verify that a request count of `1` appears.
* Browse http://localhost:8081/admin/reports/api-request-by-user/ and verify that that a request count of `1` appears for `c2@example.com`

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by kellyi** [comment]
I see the reports and everything seems to be working except that I do not see an entry added to the API request log after I make the cURL request.

**Comment by jwalgran** [comment]
Did you successfully get data back from the curl request?

**Comment by jwalgran** [comment]
If you query the `api_requestlog` table, is the record there?

**Comment by kellyi** [comment]
Yeah, data did return, but the count of rows in api_requestlog is 0.

**Comment by jwalgran** [comment]
Thanks for the review.

**Pull request merged**
