### PR TITLE
Remove most production resources

### PR DESCRIPTION
**Pull request by nanotubing**
## Overview

we're updating the terraform to remove all resources from the OAR production environment, except for cloudfront and its related DNS and certificate resources.

Connects #2376

## Demo
attached is the output from running `scripts/infra plan` in this branch
[2376_plan_output.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/10885656/2376_plan_output.txt)

## Testing Instructions

* Run a `scripts/infra plan` in this branch and review the output to verify that nothing necessary is being removed

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Comment by nanotubing** [comment]
I updated my commit, which is now also removing the infra stage from the Jenkinsfile to avoid re-creating resources in the staging environment.

It is not expected that the output of `scripts/infra plan` would have changed based on this update, but the current plan output is attached anyway.

[2376_plan_output_b.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/10902242/2376_plan_output_b.txt)

**Review by jwalgran — APPROVED** [review]
I was able to run plan against production successfully. This looks correct. There are two resources that look like we may also be able to remove.

- The SNS topic in `alarms.tf`. I do not think there are any resources remaining that publish to this topic.
- The `"internal"` hosted zone in `dns.tf` When I search in the `terraform` directory I do not see any remaining references to `internal`
- The VPC in `networking.tf`. Since our remaining resources are not within the VPC it looks like we may be able to remove this as well.

**Comment by nanotubing** [comment]
> I was able to run plan against production successfully. This looks correct. There are two resources that look like we may also be able to remove.

I pushed another commit that removes these resources. I did not get any errors in the plan output, and everything seems correct to my eyes
[2376_plan_output_c.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/10903470/2376_plan_output_c.txt)

**Review by jwalgran — APPROVED** [review]

**Comment by nanotubing** [comment]
This terraform changeset has been applied, and the OAR production environment is gone.

**Pull request merged**
