### PR TITLE
Add architecture diagrams

### PR DESCRIPTION
**Pull request by jwalgran**
## Overview

Add architecture diagrams

## Testing Instructions

* Verify the diagrams for correctness and completeness
* Verify the new README

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Review by nanotubing — APPROVED** [review]
the word Storage in the file storage bubble on the container diagram is misspelled. Other than that, this all looks great!
Screenshot 2022-12-22 at 11 19 34

The deployment diagram in particular, is impressive. There is a LOT of information packed into it, and the diagramming software did a nice job of keeping the lines seperate

**Comment by jwalgran** [comment]
Thanks. Fixed the typo in fixup  bf2bbde

**Review by TaiWilkin — APPROVED** [review]
This looks good to me. I'm not certain why CI is failing, but once that's resolved this should be good to go.

**Comment by jwalgran** [comment]
These three tests fail consistently on CI but on in my development environment and they do not fail on the `ogr/develop` branch on CI. The discrepancy between branches is most curios because this PR only adds documentation, not code.

I will not merge this until we can gather more information to avoid breaking the develop branch builds.

```
======================================================================
FAIL: test_successfully_geocoded_item_has_correct_results (api.tests.FacilityListItemGeocodingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/api/tests.py", line 1271, in test_successfully_geocoded_item_has_correct_results
    self.assertIsNotNone(item.geocoded_address)
AssertionError: unexpectedly None

======================================================================
FAIL: test_private_permission (api.tests.FacilitySubmitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/api/tests.py", line 7185, in test_private_permission
    self.assertEqual(response.status_code, 201)
AssertionError: 200 != 201

======================================================================
FAIL: test_valid_request (api.tests.FacilitySubmitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/api/tests.py", line 7123, in test_valid_request
    self.assertEqual(response.status_code, 201)
AssertionError: 200 != 201
```

I added a `pprint` statement to the `test_successfully_geocoded_item_has_correct_results` test and saw that the Google Maps API is rejecting it due to a lack of API key. Again, it is not clear why there would be a discrepancy between branches, but a solution for this specific test would be to mock the Google Maps API response, as we do in other tests. This is a better unit test practice anyway.

```
[{'action': 'parse',
  'error': False,
  'finished_at': '2022-12-22 21:20:16.453655+00:00',
  'is_geocoded': False,
  'started_at': '2022-12-22 21:20:16.451989+00:00'},
 {'action': 'geocode',
  'data': {'error_message': 'You must use an API key to authenticate each '
                            'request to Google Maps Platform APIs. For '
                            'additional information, please refer to '
                            'http://g.co/dev/maps-no-account',
           'results': [],
           'status': 'REQUEST_DENIED'},
  'error': False,
  'finished_at': '2022-12-22 21:20:16.553631+00:00',
  'skipped_geocoder': False,
  'started_at': '2022-12-22 21:20:16.453687+00:00'}]
```

**Comment by nanotubing** [comment]
we disabled a bunch of aws keys when this all went down. i don't know if that would affect this part of the code or not, but it's certainly possible?

**Comment by jwalgran** [comment]
Thanks. I did trace this to the fact that `./scripts/bootstrap` is failing because of the current Jenkins configuration. The `ogr/develop` build already has the required config in the working directory, so the fact that bootstrap is failing is not breaking the build.

**Comment by jwalgran** [comment]
Because develop branch builds are still passing due to an env file already being present from a previous successful run of `bootstrap` am going to go ahead and merge this.

**Pull request merged**
