### PR TITLE
Handle medium viewport

### PR DESCRIPTION
**Pull request by TaiWilkin**
## Overview

We had only a mobile layout and a desktop layout, and were switching to the mobile layout at medium-width screens, which particularly negatively impacted the embedded map preview. Decreases the breakpoint at which we leave the desktop view to 900px, and adjusts the view from 700px-899px to prevent overflow. Finally, switches to mobile view when under 700px.

Connects Client 114

## Demo

700px
700px

900px
900px

Embedded preview
Embed Preview

## Testing Instructions

* Run `./scripts/server`.
* Use developer tools to view the map at: 1100px; 900px; 700px; and 500px. 
* Confirm the site is useable and visually appealing at each size. 

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Comment by TaiWilkin** [comment]
@CatherineAtAzavea I've tagged you so you can look this over before I put it into formal review - let me know if you'd like me to screenshare with you with the code running so you can get a better look.

**Comment by CatherineAtAzavea** [comment]
Would it be possible to slightly decrease the padding around the search icon and the x icon under Facility Name and Data contributor (respectively)? I think that will make the text a bit easier to read. Additionally I'm seeing that the Contributor list section looks slightly indented. Other than those minor tweaks it looks good to me. Let's review via screenshare once before pushing.

**Comment by TaiWilkin** [comment]
Images of adjusted input/select adornment padding. I reduced the padding for the 'X' only at that 700-899 screen size where things are super tight, since without padding it does look a bit squished. 
Screenshot 2022-11-15 at 9 16 11 AM
Screenshot 2022-11-15 at 9 19 37 AM
I've left the contributors filter indented at least for now - it only appears when a contributor is selected, so has been indented to show the nested relationship. We can discuss when/if to remove indent in our call this afternoon.

**Comment by CatherineAtAzavea** [comment]
Looks great! Approved from UX

**Review by jwalgran — APPROVED** [review]
Excellent work. I did my width testing in the embed preview page and saw the 3-colum view now starting at 700px. The theme-based breakpoint styling is is easy to understand and looks to be nicely maintainable.

**Comment by TaiWilkin** [comment]
Thank you for the reviews!

**Pull request merged**
