### PR TITLE
WIP: Tooltip truncate component

### PR DESCRIPTION
**Pull request by designmatty**
## Overview

This is an initial stab at fixing the problems stated in the connected issue. This component will check the length of the provided string, and if it is over 40 characters, the string truncates with an ellipsis and renders a `<Tooltip>` on hover of the full string.

Connects #389 

## Demo

Screen Shot 2019-03-26 at 12 51 16 PM

## Testing Instructions

* Open a list
* Find an item with a long address and hover on it.
* Does a tooltip show up?

### CODE REVIEW

**Comment by jwalgran** [comment]
Thank you for trying to make this work. The problem with tooltips is that for this particular operation, comparing two records to see if they are a match or not, it is vital that the contributor is able to see both full names and addresses simultaneously.

**Comment by kellyi** [comment]
Not sure if we should do it here or in a separate changeset but it seems like we could drop or drastically narrow the CSV ROW INDEX column since it occupies a disproportionate amount of space:

Screen Shot 2019-03-29 at 1 36 17 PM

**Comment by kellyi** [comment]
Seems like that gets partway to a fix:

Screen Shot 2019-03-29 at 1 43 36 PM

**Comment by jwalgran** [comment]
The row index is a helpful reference when paging through a long list. I don't want to drop it, but our longest lists are in the thousands, so we only need enough width to show 4 characters. We could shorten the header to just "Row"

**Comment by designmatty** [comment]
The only way I can imagine this getting fixed without the use of truncation/tooltips would require a complete rewrite of how we handle these tables. It would be a substantial amount of work and I don't feel we have the time to do it currently.

**Comment by kellyi** [comment]
> The only way I can imagine this getting fixed without the use of truncation/tooltips would require a complete rewrite of how we handle these tables.
 
I'm going to take a small amount of time to see what changes can be made to the existing table to make this mostly workable on Macbook-sized screens. I think there is currently quite a bit of unused space in on the table screen and so I think it's possible we can get it most of the way there for now without undertaking a complete rewrite, which we can decide whether we want to do later.

**Comment by designmatty** [comment]
@kellyi You might be able to do something where you get the string length, and if it is cover a specified amount, change the max-height of the containing div. That hard defined div height is what ultimately causes the overflow issues. If you'd like to pair on this at all, let me know.

**Comment by jwalgran** [comment]
Thanks for taking the time to dig into this issue. I agree with the assessment that we need to restructure the table. We have decided to keep #389 in the backlog for now.

**Pull request closed without merging**
