### PR TITLE
Allow Postgres to be accessible from host machine

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

This allows the use of custom Postgres GUI clients, such as [Postico](https://eggerapps.at/postico/), to be used to inspect the database.

## Demo

image

### CODE REVIEW

**Comment by rbreslow** [comment]
@jeancochrane Does this have the potential to effect what was done in https://github.com/open-apparel-registry/open-apparel-registry/pull/171?

**Comment by rajadain** [comment]
I'll wait until we have clarification on the above.

**Comment by jeancochrane** [comment]
Thanks for flagging this @rbreslow, I agree that publishing the database ports in the Compose file will cause collisions on CI.

If isolating database inspection in a separate script would work for dev needs, we could bring up the database with something like `docker-compose run -p 5432:5432 database` in order to temporarily publish the ports. We could also use an override Compose file to similar effect. Happy to help vet ideas if it would be useful for moving this PR along.

**Comment by rbreslow** [comment]
@jeancochrane In an ideal world, we should be able to publish the PostgreSQL service ports without requiring a separate script. How do you feel about reopening azavea/operations#284?

**Comment by rajadain** [comment]
Would adding the `database` service to `docker-compose.ci.yml` without the port revelation take care of this? As done in 94e0229? I suppose this causes some redundancy and we'd need to update the settings in two files instead of one, which is less than ideal.

I'd also be up for having a separate script for making the database inspectable, as suggested above.

**Comment by rajadain** [comment]
Closing this for now. I'll do the changes locally for when I need them.

**Pull request closed without merging**
