### PR TITLE
Make miscellaneous bugfixes

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

- show RouteNotFound for non-existent profiles
- don't translate contributor name and type in search menus
- suppress `claim/` route from facilities API documentation
- adjust facility details back button to go back to the main facilities/ route
- update contributor name hint text on registration form

Connects #565 
Connects #606
Connects #613 
Connects #569 
Connects #120 

## Testing Instructions

- serve this branch
- visit http://localhost:6543/profile/70000 and verify that you see the route not found component
- visit http://localhost:6543 and change the language to Esperanto and verify that the contributor names and contributor types sections aren't translated
- sign in as c1@example.com then visit localhost:8081/admin and turn on the claim a facility switch
- visit http://localhost:8081/api/docs/#/facilities and verify that you do not see a POST endpoint for `claim/`
- sign out then sign in as c2@example, search for a facility, and claim it
- fill out the claim form completely; when you reach the last page, click the in-app back button on the claim form
- when you return to the facility details page, click that in-app back button and verify that it takes you to the main facilities search

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by kellyi** [comment]
I also adjusted the "Contributor Name" hint on the registration form with the suggested text from #120:

Screen Shot 2019-06-21 at 2 12 39 PM

**Comment by kellyi** [comment]
Looking at that again I realized I placed the new text on the wrong hint, so I'll adjust.

**Comment by kellyi** [comment]
Alright:

Screen Shot 2019-06-21 at 2 20 16 PM

**Comment by jwalgran** [comment]
Looking at this now.

**Comment by jwalgran** [comment]
The `facility-claims` API endpoints are also undocumented. Do you think that we should add an issue to document them, or remove that viewset from the docs as well?

**Comment by kellyi** [comment]
> The facility-claims API endpoints are also undocumented. Do you think that we should add an issue to document them, or remove that viewset from the docs as well?

I think there are a couple that are administrator-only that we probably want to remove regardless, so my inclination is just to remove all of them for now and if we decide to restore some of them later we can document them then?

**Comment by kellyi** [comment]
eb1af151326160b0b4c79abd3ac21099d6031fb4 removes the FacilityClaimsViewset from the API docs.

**Comment by kellyi** [comment]
Thanks!

**Pull request merged**
