### PR TITLE
Increase the max length of FacilityListItem.geocoded_address

### PR DESCRIPTION
**Pull request by jwalgran**
## Overview

We were running into crashes in the geocoding process because we were trying to insert more than 200 characters into the `geocoded_address` field. The value of this field comes from the `formatted_address` field in the Google geocoder response. We could not find any documentation mentioning how long this field might be so we took a guess and made the field 5x larger that it was.

Connects #342 
Connects #292

## Testing Instructions

I was not able to reproduce the issue with 14.csv as reported in #292. I was able to reproduce it with 
[handm-long-geocode-test.csv.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/2990307/handm-long-geocode-test.csv.txt)

* On `develop`, upload [handm-long-geocode-test.csv.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/2990307/handm-long-geocode-test.csv.txt) and run it through `parse` and `geocode` Verify that an exception is raised.
* Checkout this branch and `./scripts/manage migrate`
* Run the `geocode` process again and verify that it completes without error (some items may "fail" because they were previously geocoded successfully)

### CODE REVIEW

**Comment by jwalgran** [comment]
I updated the test instructions and attached a file that can be used to reproduce the error.

**Comment by rajadain** [comment]
Taking a look now.

**Comment by rajadain** [comment]
Unfortunately I'm unable to reproduce the issue on `develop`. Tried both `14.csv` and `handm-long-geocode-test.csv`.

**Comment by jwalgran** [comment]
Interesting. I assume that the responses from the Google are changing out from under us.

I used this diff to force the error on develop.


```diff
diff --git a/src/django/api/processing.py b/src/django/api/processing.py
index eec5036..e5d6745 100644
--- a/src/django/api/processing.py
+++ b/src/django/api/processing.py
@@ -92,7 +92,7 @@ def geocode_facility_list_item(item):
                     data["geocoded_point"]["lng"],
                     data["geocoded_point"]["lat"]
                 )
-                item.geocoded_address = data["geocoded_address"]
+                item.geocoded_address = ('A' * 150) + data["geocoded_address"]
             else:
                 item.status = FacilityListItem.GEOCODED_NO_RESULTS
             item.processing_results.append({
```

**Comment by rajadain** [comment]
Great, I'll try that.

**Comment by jwalgran** [comment]
Thanks for the review.

**Pull request merged**
