### PR TITLE
Add django-simple-history

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

- add django-simple-history library
- create HistoricalFacility audit model
- display history log for Facility on Django admin

Connects #519 

## Demo

Screen Shot 2019-05-16 at 11 02 05 AM
Screen Shot 2019-05-16 at 11 02 54 AM
Screen Shot 2019-05-16 at 11 02 30 AM

## Testing Instructions

On this branch
- `./scripts/update`
- `./scripts/manage resetdb`
- `./scripts/manage processfixtures`
- `./scripts/manage createsuperuser`
- `./scripts/server`
- sign into the django admin
- visit a Facility object and verify that you can see its history
- update a facility, then verify that you can see and revert the change
- use `./scripts/manage shell_plus` to interact with a HistoricalFacility object

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by jwalgran** [comment]
Looking at this now

**Comment by jwalgran** [comment]
The docs mention the included management command that will create the initial history for existing records.
https://django-simple-history.readthedocs.io/en/2.7.2/quick_start.html#existing-projects

We should consider creating a 2.4.0 release issue now and adding the running of this management command as a step after running the migrations. What do you think?

**Comment by kellyi** [comment]
> We should consider creating a 2.4.0 release issue now and adding the running of this management command as a step after running the migrations. What do you think?

Sounds good to me -- it'll help make sure we don't lose track of the migration related work.

**Comment by kellyi** [comment]
I made https://github.com/open-apparel-registry/open-apparel-registry/issues/522 for the release and noted the extra step in a comment there.

**Comment by kellyi** [comment]
Cool, thanks! I'll run the migration via ecsmanage after merging this. We'll still need to run the command to populate it afterwards.

**Pull request merged**
