### PR TITLE
Implement server side paging for facility list items

### PR DESCRIPTION
**Pull request by jwalgran**
## Overview

We were running into gateway timeout issues when attempting to load all items for a large list (thousands of rows)

To solve this we have added a separate endpoint for fetching list items and implemented paging based on the built-in Django REST Framework paging support.

We were able to reuse the bulk of the client side paging logic but we now fetch new data when the page or page size is changed rather than just getting a slice of the full data in memory.

Connects #335

## Notes

This breaks the client side CSV downloading. This is logged as a separate issue (#344) and will be fixed in a follow up PR

## Testing Instructions

* Log in as c8@example.com
* Browse http://localhost:6543/lists/8
* Use the React tools in the developer console to verify that only 20 rows have been loaded into the state
* Use the page navigation and verify that the data is correctly paged.

### CODE REVIEW

**Comment by jwalgran** [comment]
Posted a draft for some early feedback. The pagination is working but I need to fix the CSV download feature so it requests all the data one page at a time and joins it together.

**Comment by jwalgran** [comment]
Assigned to @kellyi because he built the original paging.

**Comment by kellyi** [comment]
Setting this up to try it out!

**Comment by kellyi** [comment]
I've been testing this out and it's working great so far. I've tried out a 1700 item list and am currently setting up a 2900 item list and the paging works for all the cases I've tried:

- changing the page size or page number behaves correctly
- refreshing with the querystring params load the correct page
- the table renders correctly

This is probably known but just in case it's not: it looks like there's a propTypes error and a stray console.log statement:

Screen Shot 2019-03-20 at 11 38 49 AM

We should fix the proptypes error by just dropping the `.isRequired` suffix.

If we'd like, we could potentially spin off the CSV downloading to another card in the interest of expediting getting this onto staging for more user testing.

**Comment by jwalgran** [comment]
>If we'd like, we could potentially spin off the CSV downloading to another card in the interest of expediting getting this onto staging for more user testing.

I do think it is wise to merge this before fixing downloads since it is a bit of a showstopper

**Comment by kellyi** [comment]
I found a bug when trying to confirm/reject a facility match:

Screen Shot 2019-03-20 at 11 58 11 AM

The request goes through correctly to the API but it appears to be crashing on updating the app state afterward.

**Comment by jwalgran** [comment]
facepalm
Posted a bit too early. Thanks. Will fix up these bugs.

**Comment by jwalgran** [comment]
>We should fix the proptypes error by just dropping the .isRequired suffix.

Addressed in fixup aa30fc0

>I found a bug when trying to confirm/reject a facility match:

Addressed in fixup ac49218

>it looks like there's [...] a stray console.log statement

Addressed in fixup 7716228

**Comment by jwalgran** [comment]
Fixed up and ready for review

**Comment by kellyi** [comment]
Cool, about to test this again.

**Comment by jwalgran** [comment]
Thanks for the review and the well-designed paging UI that was easily repurposed.

I squashed the fixups and will merge when the update passes CI.

**Pull request merged**
