### PR TITLE
Upgrade terraform to 1.1.9

### PR DESCRIPTION
**Pull request by nanotubing**
## Overview
A terraform upgrade was necessary for a desired feature surfaced from work in another PR in the parent issue. 

Connects #1998 

## Notes
This was a multi-step upgrade that involved jumping through multiple versions to minimize the amount of code changes necessary at each step. Due to the nature of the upgrade, the terraform code was applied at each step, so code covered by this PR is currently in place on the OSH staging environment.

## Testing Instructions
This code is currently deployed to staging, so testing should be done as a verification of the changes.

* ensure that jenkins completed successfully
* review the console output in jenkins to verify that nothing was changed that affects the functioning of the site
* navigate the staging site to ensure correct functionality
* submit a list to ensure that submitted lists are processing correctly.

## Checklist

- [ ] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [ ] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Comment by nanotubing** [comment]
a warning in the terraform upgrade flagged these five variables in the .tfvars file because they're defined, but not used anywhere. We've commented out the 5 relevant lines for now:
 
```
tile_ecs_desired_count
tile_ecs_deployment_min_percent 
tile_ecs_deployment_max_percent
tile_fargate_cpu
tile_fargate_memory
```

**Comment by jwalgran** [comment]
I believe that the `tile_` variables were related to this experimental PR that was never put into production https://github.com/open-apparel-registry/open-apparel-registry/pull/1107

**Comment by jwalgran** [comment]
I changed the title of the PR to `Upgrade terraform to 1.1.9` to more accurately reflect the upgrade.

**Review by jwalgran — APPROVED** [review]
I verified that Jenkins passed and successfully verified the following:
- Account registration
- Search and download
- List submission and processing

**Pull request merged**
