### PR TITLE
Prepare OAR code for read-only database

### PR DESCRIPTION
**Pull request by mstone121**
## Overview

This PR updates the UI and some of the django API in preparation for making the database read only.

Connects #2160 

## Demo

Screen Shot 2022-09-28 at 11 39 58 AM

## Notes

The facility download logic was embedded in the `logDownload` reducer so it and related actions were renamed to `facilityDownload`.

There might be additional components/tests/views that I missed that can be deleted, but the UI should not utilize these features.

## Testing Instructions

* Go to homepage
* Contribute/Register button should be greyed out and unclickable.
* Log in
* Contribute button should be greyed out and unclickable
* Go to a facility page
* The facility CTA's at the bottom of the side bar should be removed
* Go to an unclaimed facility page
* The "Claim facility" header should not be present
* Attempt to go to user settings
* A "Not available" message should be displayed instead
* Go to My Facilities
* Facility claim details should not be viewable

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Comment by jwalgran** [comment]
CI failed due to some lint

```
Creating open-apparel-registry-pr-2184_django_run ... 
Creating open-apparel-registry-pr-2184_django_run ... done
./api/views.py:76:1: F401 'api.models.DownloadLog' imported but unused
./api/tests.py:7357:17: F821 undefined name 'RequestLog'
./api/tests.py:7373:13: F821 undefined name 'RequestLog'
./api/tests.py:7374:13: F821 undefined name 'RequestLog'
./api/tests.py:7398:13: F821 undefined name 'RequestLog'
./api/tests.py:7399:13: F821 undefined name 'RequestLog'
```

**Comment by TaiWilkin** [comment]
Working great! It also looks good in embedded map mode. 

Consider lowering the popup menu a bit to reflect the addition of the banner:
Screen Shot 2022-09-29 at 11 50 04 AM

This isn't specifically mentioned in the issue, but I think we'll want to disable/remove the action buttons on facility lists:
Screen Shot 2022-09-29 at 12 02 08 PM

**Review by TaiWilkin — APPROVED** [review]
Minor recommended changes listed above.

**Comment by mstone121** [comment]
@TaiWilkin

- [4dfadb4](https://github.com/open-apparel-registry/open-apparel-registry/pull/2184/commits/4dfadb47804796faa48bd6984407fca0242ac45b) for submenu offset
- [5cf3ff7](https://github.com/open-apparel-registry/open-apparel-registry/pull/2184/commits/5cf3ff75c57015d9e6c564bb42fa19ce9c93234c) for removal of list action items. Is there an easy way to test this? The super user I created couldn't upload a list: `User contributor cannot be None`

**Comment by TaiWilkin** [comment]
Looks perfect!
Screen Shot 2022-10-03 at 9 30 29 AM

On OAR, lists are confirmed by regular users, so you can login as any regular user with a list (c3@example.com has one by default).

For testing similar things on OSHub, you can login and create a list as any user, then view the list as an admin (c1@example.com). I'll often have a regular user open in one window, and c1@example.com logged in on an incognito browser, so I don't have to log in and out a million times.

**Comment by mstone121** [comment]
@jwalgran @TaiWilkin I should hold off on merging this, correct? It should be merged when we're ready to make the OAR DB read-only.

**Comment by jwalgran** [comment]
Correct. We will merge this, then make and deploy a release on Friday October 14

**Comment by jwalgran** [comment]
I will go ahead and merge this to expedite the release process. Thanks.

**Pull request merged**
