### PR TITLE
Update footer for OS Hub

### LINKED ISSUE #2123: Dual Scrollbars on OSH Staging frontpage
## Overview

I just loaded the OSH Staging site at the current URL, and it loaded with two scrollbars, both scrolling the expanded sidebar.

I confirmed by reloading the site in a private window, and ruled out extension-related malfeasance by disabling them one by one, reloading each time to confirm that the issue is still present.

For this, my browser window was the full allowable height of the monitor, stretching from the bottom of the menu bar, to the bottom edge of the screen

Firefox 104.0.1 (64-bit)
macOS 12.5.1 (21G83)
Display: 24" DELL U2415 at 1920 × 1200

### Expected Behavior

There should be only one scrollbar

### Actual Behavior

There are two scrollbars both scrolling the same content

### Steps to Reproduce

* instructions for reproducing the bug
* prefer bulleted list
* describe the environment: device, os, browser/runtime

### Demo
Screen Shot 2022-09-06 at 14 06 25

### LINKED ISSUE #2174: Sidebar content does not scroll in mid-sized screen mode
## Overview

The sidebar content on the home page does not scroll in mid-sized screen mode. 

Maybe related to https://github.com/open-apparel-registry/open-apparel-registry/issues/2123.

### Expected Behavior

The content should scroll.

### Actual Behavior

No scroll bar and not scrollable.

### Steps to Reproduce

* Resize window to enter mid-size mode.
* Make sure the height of the window is small enough to cover some of the content.
* Attempt to scroll home page sidebar

### Demo

https://user-images.githubusercontent.com/8356789/192599163-d372e7ae-7c3b-43cb-abba-5d38d09eb81b.mov

You can't tell from the screen capture, but I'm attempting the scroll at the end.

### PR DESCRIPTION
**Pull request by mstone121**
## Overview

This PR updates the site footer with the [design from N&S](https://codepen.io/niceandserious/pen/dyeOdmY/1a08d126f3479db9d98d55fda4539a74).

Connects #2079 
Closes #2123 
Closes #2174 

## Demo

Screen Shot 2022-09-28 at 2 30 17 PM

## Notes

This PR changes the main content from `position: fixed` to `position: static`. This does affect the way the rest of the web page feels. It also fixes the bugs raised in issues #2123 and #2174.

The header needs an increased `z-index` now that it appears over the map while scrolling.

## Testing Instructions

* Go to the home page and verify the footer matches the design and the links work correctly
* Make sure the header looks correct on other pages too

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] This PR is targeted at the correct branch (`develop` vs. `ogr/develop`)
- [ ] If this PR applies to both OAR and OGR a companion PR has been created

### CODE REVIEW

**Review by TaiWilkin — CHANGES_REQUESTED** [review]
The footer looks great! The scrolling on the homepage is very smooth, and in general scrolling and resizing worked well. 

The one bug I'm seeing is that on http://localhost:6543/facilities I can't see the map on either desktop or mobile. @jacobscarfmerrell had some issues with this previously as well, so might have some idea of why it's not displaying.

**Comment by mstone121** [comment]
I was able to fix the `/facilities` bug by removing the height, width, and position attributes from the map component. The map then showed up, but it would stretch to the length of the filters and facilities lists. I added maxHeights for these elements and scroll overflow for the filters. See https://github.com/open-apparel-registry/open-apparel-registry/pull/2189/commits/1c3449b67827e31f926bdf02911cbc977894308a for details.

**Comment by mstone121** [comment]
Looks like adding `results-height-subtract` to the translate bar fixes the issue. https://github.com/open-apparel-registry/open-apparel-registry/pull/2189/commits/59cdb635f431fdebe9ca8db1edada3e393c70604

**Review by TaiWilkin — APPROVED** [review]
Looks good!

**Review by jwalgran — COMMENTED** [review]
On the search results page I see some extra while space below the tooter. Searching for text that does not match any facilities is a quick way to reproduce it

**Review by jwalgran — CHANGES_REQUESTED** [review]
I see the map missing on the facility details page

Screen Shot 2022-09-29 at 10 50 58 AM

**Comment by mstone121** [comment]
> On the search results page I see some extra while space below the tooter. Searching for text that does not match any facilities is a quick way to reproduce it

I'm not able to reproduce this, even with a no facilities search.

I was able to fix the disappearing interactive map with https://github.com/open-apparel-registry/open-apparel-registry/pull/2189/commits/f1823aead345589a98d75954ac825a167387dc6b.

**Review by jwalgran — APPROVED** [review]

**Review by jwalgran — APPROVED** [review]
At the responsive size Tai mentioned (1300x606) I no longer see the whitespace below the footer
Screen Shot 2022-10-03 at 12 41 39 PM

**Pull request merged**
