### PR TITLE
Allow prefer contributor name in embed

### PR DESCRIPTION
**Pull request by TaiWilkin**
## Overview

Adds a field to the embedded map config model allowing users to choose
to prefer their own contributed facility name over the default
facility name. In the EmbeddedMap, the facility name (not the address) of the facility
that was contributed by the embedded map's contributor is
promoted to the primary position. This is only be in effect in the
embedded map view, and not in the full site. If the contributor has
multiple active list items for the facility, we prefer first any that
match the assigned facility name, or secondly the most submission.

Connects #1550 

## Demo
Screen Shot 2021-12-10 at 4 15 45 PM
Screen Shot 2021-12-10 at 4 15 50 PM
Screen Shot 2021-12-10 at 4 33 35 PM

## Notes

@lederer I adjusted the section hierarchy of the Embed settings page to add the new field checkbox as a separate subsection under a larger "fields" category, similar to the pattern in the Theme section. 

## Testing Instructions

* Create an embedded map config for a contributor.
* Run `./scripts/migrate`. Confirm the embed config you created before now has the field `prefer_contributor_name=false`
* Update a facility list item created by the contributor to have a different name from the associated facility
* View that facility in the facilities search and in its details page and confirm the name has not changed in the display
* Go to the embed config settings page for that contributor. The prefer contributor name checkbox should be false. 
* View the embed preview; the facility name in the list and details should be the same.
* Check the prefer contributor name box and the view the embed preview again. The facility name in the list and details should be the alternate name assigned to the list item. 

## Checklist

- [x] `fixup!` commits have been squashed
- [x] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by lederer** [comment]
> @lederer I adjusted the section hierarchy of the Embed settings page to add the new field checkbox as a separate subsection under a larger "fields" category, similar to the pattern in the Theme section.

👍

**Review by jwalgran — APPROVED** [review]
Works perfectly. Nice job.

**Comment by jwalgran** [comment]
I did run into an error trying to reverse the migration to test a different PR. Since we are adding a column, specifying an empty function as the "reverse" for our default value setting function does the trick.

```diff
diff --git a/src/django/api/migrations/0074_embedconfig_prefer_contributor_name.py b/src/django/api/migrations/0074_embedconfig_prefer_contributor_name.py
index 2936102..4b85b17 100644
--- a/src/django/api/migrations/0074_embedconfig_prefer_contributor_name.py
+++ b/src/django/api/migrations/0074_embedconfig_prefer_contributor_name.py
@@ -10,6 +10,10 @@ def set_prefer_contributor_name_false(apps, schema_editor):
         config.save()
 
 
+def do_nothing_on_reverese(apps, schema_editor):
+    pass
+
+
 class Migration(migrations.Migration):
 
     dependencies = [
@@ -22,5 +26,5 @@ class Migration(migrations.Migration):
             name='prefer_contributor_name',
             field=models.BooleanField(blank=True, help_text="Whether to use the contributor's facility name before other names.", null=True),
         ),
-        migrations.RunPython(set_prefer_contributor_name_false)
+        migrations.RunPython(set_prefer_contributor_name_false, do_nothing_on_reverese)
     ]

```

**Comment by TaiWilkin** [comment]
The migration has been updated. Thank you for reviewing!

**Pull request merged**
