### PR TITLE
Miscellaneous UI fixes

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

- Fix contributor form troubleshooting typo / Connects #381
- Left-align facility list items guide text snippet / Connects #382 
- Show country name in facility details address / Connects #375 
- Reroute to facilities on login / Connects #376 
- Conditionally redirect to facilities map on logout / Connects #343 
- Restrict map bounds to tile extent / Connects #365 
- Autofocus first user input on forms / Connects #273 
- Update Guide tab panel text / Connects #383 

## Testing

- for each of the issues above, verify that the UI issue has been remedied by the changes here.

### CODE REVIEW

**Comment by kellyi** [comment]
@designmatty for https://github.com/open-apparel-registry/open-apparel-registry/pull/385/commits/57a4836d1e3d2e7a91c5a8854354e634a2b064a4 I had to disable an ESLint rule about not using the `autoFocus` prop.

In this case, I am using it to focus the first field of form inputs -- which is, I think, the correct behavior -- but can you concur that it's okay from an accessibility perspective for me to disable the linting rule for that specific line in this specific circumstance?

**Comment by rajadain** [comment]
Seeing this error in the console:

image

**Comment by kellyi** [comment]
That error's from a bug or quirk of how react-router sees the NoRouteMatch component. I fixed it in a commit on this PR:

https://github.com/open-apparel-registry/open-apparel-registry/pull/353

**Comment by kellyi** [comment]
Specifically: https://github.com/open-apparel-registry/open-apparel-registry/pull/353/commits/669d756b9720b70eebcf07facfb422f7c95eef86

Unfortunately that error is also currently on develop, but it's non-breaking and it's coming from a library, not our code.

**Comment by rajadain** [comment]
This may be worth its own card, but here's an odd behavior I noticed:

* Be logged out
* Search for a facility
* See it in the search results
* Log in
* Be redirected to search results, but now they are empty
* Search again to see them populated



If instead of being redirected to the search results, I was redirected to an empty state, that would've been better. Or, the search results should've stuck around.

**Comment by kellyi** [comment]
> This may be worth its own card, but here's an odd behavior I noticed:

Makes sense. Can you write this up as its own card? This is how things work on `develop`, too.

**Comment by kellyi** [comment]
I think the fix might be to reset the selected tab in the UIReducer when necessary so it'll default back to the search tab.

**Comment by rajadain** [comment]
I don't see a login link when going to a facility detail page if I'm logged out, as asked for in #343 

image

**Comment by kellyi** [comment]
> I don't see a login link when going to a facility detail page if I'm logged out

Thanks for catching. I added this in 

c6b80cc8bf15fd18660d4fafc22c02782813d936

Screen Shot 2019-03-25 at 4 43 16 PM

**Comment by kellyi** [comment]
Cool, thank you for testing!

**Comment by kellyi** [comment]
I updated the commit message for the commit which includes the autoFocus prop and turns off the jsx-a11y linting for the relevant line. We checked into it and because we are using the prop to make the forms behave as normal forms, it appears to be a blessed use of the `autoFocus` prop there.

**Pull request merged**
