### PR TITLE
Search custom_text in embedded map

### PR DESCRIPTION
**Pull request by emilyhu0106**
## Overview

Allows free text search on an embedded map in the custom_text field

Connects #1536

## Notes

- `embed` is passed to `VectorTileFacilitiesLayer` and `VectorTileFacilityGridLayer` to make sure that the facility markers are shown individually at both high zoom level and in the hex grid clustering at lower zoom level
- The custom text field was not being correctly updated to empty when all of the fields for that facility had been marked un-searchable. We now correct remove the custom_text for the facility in that case in #1631.

## Testing Instructions

* Checkout this branch and run `./scripts/server`
* In an incognito browser, navigate to [the admin](http://localhost:8081/admin/api/contributor/2/change/) log in as c1@example.com
* Update Service Provider A to have deluxe embed permissions
* In another window, login as [c2@example.com](mailto:c2@example.com)
* Contribute [oar-custom-text.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8006223/oar-custom-text.csv)
* Fully process the list with: `./tools/batch_process {list-id}` (the ID is 17 for me)
* Go to embed config settings, make ‘custom_field’ and ‘custom_field_2’ visible and searchable
* Navigate to [embedded map](http://localhost:6543/contributors=2&embed=1) and search "test" for custom field
    - [x] Search "test" for custom field and get two results - Hamster Home and Guinea Garden
    - [x] Search "Home" and "Garden" for the name field and should get one result respectively
* Navigate to [OAR search page](http://localhost:6543/)
    - [x] Search "test" for custom field and get zero results since custom text search is disabled for non-embedded mode
    - [x] Search "Home" and "Garden" for the name field and should get one result respectively

## Checklist

- [ ] `fixup!` commits have been squashed
- [ ] CI passes after rebase
- [x] CHANGELOG.md updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines

### CODE REVIEW

**Comment by emilyhu0106** [comment]
I am experiencing a weird [behavior](https://github.com/open-apparel-registry/open-apparel-registry/pull/1629)[](https://files.slack.com/files-pri/T029GD0MJ-F031JPFJX5M/image.png)[](https://files.slack.com/files-pri/T029GD0MJ-F031JPFJX5M/download/image.png)[](https://files.slack.com/files-pri/T029GD0MJ-F032C1LPKMX/image.png) for the custom_text search. I can perform the custom field search successfully but the marker won’t appear all the time. If the facilities with the custom field matched are the only one matching (e.g. search “test”), then the marker won’t show up

image

when there are other facilities that have their name matched (e.g. search “2"), the markers will show up (in 2nd pic).

image

 I got no explicit error in browser console or terminal

**Comment by jwalgran** [comment]
The first thing to check would be that we are sending the `embed=1` query parameter along with the vector tile requests.

**Comment by TaiWilkin** [comment]
Taking a look now

**Review by TaiWilkin — APPROVED** [review]
Working well and reads cleanly! 
Friendly reminder to squash fixups before merging!

**Comment by emilyhu0106** [comment]
> Friendly reminder to squash fixups before merging!

Is this better to separate the front-end and back-end into two commits? There is not much changes but across 4 files

**Comment by TaiWilkin** [comment]
@emilyhu0106 I think it's fine to keep it as one commit for this one, since the change-set is so small.

**Pull request merged**
